
server:
   port: 8080
   servlet:
      contextPath: /aps
spring:
<<<<<<< Updated upstream
  application:
    name: aps
  datasource:
    url: jdbc:postgresql://localhost:5432/aps
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456   
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
      
=======
   application:
      name: aps
   profiles:
      active: dev
      
>>>>>>> Stashed changes
